process.env.DATA_DIR = `/tmp/rs-season-scoring-integration-${process.pid}`;
process.env.SESSION_SECRET = "test-secret-that-is-at-least-32-chars-long";
process.env.NODE_ENV = "test";
process.env.APP_MODE = "self_hosted";
import test from "node:test";
import assert from "node:assert/strict";
const { db } = await import("../src/db.js");
const { totalScore } = await import("../src/repositories/score-ledger.js");
const { insertWatch } = await import("../src/repositories/watch-repository.js");
const { logManualWatchAndReconcile } = await import("../src/services/manual-watch-service.js");
const { reconcileMovieEligibility } = await import("../src/services/scoring-service.js");
const { reconcileSeasonScoresForUser } = await import("../src/services/season-scoring-service.js");
const { importHistory, previewPlaceholderReconciliation, applyPlaceholderReconciliation } = await import("../src/sync.js");
const { resolveDuplicateCase } = await import("../src/services/duplicate-service.js");
const { deleteWatchAndReconcileAchievements } = await import("../src/services/achievement-service.js");
const { updateUserSettings } = await import("../src/services/user-settings-service.js");
const { createLeague, createInvite, acceptInvite, leaveLeague } = await import("../src/services/league-service.js");
let n=0;
const movie=id=>({id,title:`Film ${id}`,poster_path:null,vote_average:7,runtime:120,release_date:"2000-01-01",genres:[{name:"Drama"}],belongs_to_collection:null,credits:{cast:[],crew:[]}});
const getMovie=async id=>movie(id); const event=(tmdb_id,watched_at,event_id)=>({tmdb_id,watched_at,event_id});
function user(p="u",timezone="UTC"){return Number(db.prepare("INSERT INTO users(username,password_hash,timezone) VALUES (?,'x',?)").run(`${p}-${process.pid}-${++n}`,timezone).lastInsertRowid)}
function league(owner,name=`L${n}`){const l=createLeague(owner,{name,timezone:"UTC",default_mode:"casual"});return{...l,membershipId:db.prepare("SELECT id FROM league_memberships WHERE league_id=? AND user_id=? AND left_at IS NULL").get(l.id,owner).id}}
function season(owner,l,{participant=owner,membership=l.membershipId,mode="casual",starts="2035-01-01T00:00:00.000Z",ends="2035-02-01T00:00:00.000Z"}={}){const id=Number(db.prepare("INSERT INTO seasons(league_id,name,mode,timezone,rule_version,starts_at,ends_at,created_by_user_id,created_at,updated_at) VALUES (?,?,?,'UTC','season-v1',?,?,?,?,?)").run(l.id,`S${n}`,mode,starts,ends,owner,starts,starts).lastInsertRowid);db.prepare("INSERT INTO season_members(season_id,membership_id,user_id,username_snapshot,eligible_from,created_at) VALUES (?,?,?,?,?,?)").run(id,membership,participant,`u${participant}`,starts,starts);db.prepare("UPDATE seasons SET participants_locked_at=?,updated_at=? WHERE id=?").run(starts,starts,id);return{id}}
const roots=sid=>db.prepare("SELECT * FROM score_events WHERE season_id=? AND projection_source_event_id IS NOT NULL AND reverses_event_id IS NULL AND reversed_at IS NULL ORDER BY effective_at,id").all(sid);
function fail(sid,name){db.exec(`CREATE TEMP TRIGGER ${name} BEFORE INSERT ON score_events WHEN NEW.season_id=${sid} BEGIN SELECT RAISE(ABORT,'forced season projection failure'); END;`)}
const drop=name=>db.exec(`DROP TRIGGER ${name}`);

test("manual late history reconciles the entire movie chronology across season boundaries",async()=>{const uid=user("chronology"),l=league(uid),jan=season(uid,l),mar=season(uid,l,{starts:"2035-03-01T00:00:00.000Z",ends:"2035-04-01T00:00:00.000Z"});await logManualWatchAndReconcile(uid,movie(41001),{watchedAt:"2035-03-15T12:00:00Z"});const old=roots(mar.id)[0]?.projection_source_event_id;await logManualWatchAndReconcile(uid,movie(41001),{watchedAt:"2035-01-15T12:00:00Z"});assert.equal(totalScore(uid,{seasonId:jan.id}),49);assert.equal(totalScore(uid,{seasonId:mar.id}),12);assert.notEqual(roots(mar.id)[0].projection_source_event_id,old)});

test("manual source, lifetime ledger, and projection roll back together and retry",async()=>{const uid=user("manual-rollback"),s=season(uid,league(uid));fail(s.id,"fail_manual");await assert.rejects(logManualWatchAndReconcile(uid,movie(41002),{watchedAt:"2035-01-10T12:00:00Z"}),/forced season/);drop("fail_manual");assert.equal(db.prepare("SELECT COUNT(*) c FROM watches WHERE user_id=? AND tmdb_id=41002").get(uid).c,0);assert.equal(db.prepare("SELECT COUNT(*) c FROM score_events WHERE user_id=?").get(uid).c,0);await logManualWatchAndReconcile(uid,movie(41002),{watchedAt:"2035-01-10T12:00:00Z"});assert.equal(roots(s.id).length,1)});

test("verification-only provider import repairs verified projection when imported is zero",async()=>{const uid=user("verified"),s=season(uid,league(uid),{mode:"verified"});insertWatch({userId:uid,movie:movie(41003),source:"plex",watchedAt:"2035-01-11T12:00:00Z"});reconcileMovieEligibility(uid,[41003]);assert.equal(roots(s.id).length,0);fail(s.id,"fail_verification");await assert.rejects(importHistory(uid,"plex",[event(41003,"2035-01-11T12:00:00Z","event")],getMovie,{connectionId:"acct"}),/forced season/);drop("fail_verification");assert.equal(db.prepare("SELECT provider_event_id FROM watches WHERE user_id=? AND tmdb_id=41003").get(uid).provider_event_id,null);const r=await importHistory(uid,"plex",[event(41003,"2035-01-11T12:00:00Z","event")],getMovie,{connectionId:"acct"});assert.deepEqual([r.imported,r.verified],[0,1]);assert.equal(roots(s.id).length,1);assert.equal(JSON.parse(roots(s.id)[0].metadata_json).evidence_kind,"direct_provider")});

test("duplicate resolution and projection are atomic, idempotent, and retryable",async()=>{const uid=user("duplicate"),s=season(uid,league(uid),{mode:"verified"});await logManualWatchAndReconcile(uid,movie(41004),{watchedAt:"2035-01-12T10:00:00Z"});await importHistory(uid,"plex",[event(41004,"2035-01-12T12:00:00Z","dup")],getMovie,{connectionId:"dup"});const d=db.prepare("SELECT * FROM duplicate_cases WHERE user_id=? AND status='pending'").get(uid);assert.equal(roots(s.id).length,0);fail(s.id,"fail_dup");await assert.rejects(resolveDuplicateCase(uid,d.id,"merge"),/forced season/);drop("fail_dup");assert.deepEqual(db.prepare("SELECT status,resolution FROM duplicate_cases WHERE id=?").get(d.id),{status:"pending",resolution:null});assert.equal(db.prepare("SELECT deleted_at FROM watches WHERE id=?").get(d.candidate_watch_id).deleted_at,null);await resolveDuplicateCase(uid,d.id,"merge");const count=db.prepare("SELECT COUNT(*) c FROM score_events WHERE season_id=?").get(s.id).c;await resolveDuplicateCase(uid,d.id,"merge");assert.equal(db.prepare("SELECT COUNT(*) c FROM score_events WHERE season_id=?").get(s.id).c,count);assert.equal(roots(s.id).length,1)});

test("pending duplicate cancellation on deletion reconciles atomically",async()=>{const uid=user("delete"),s=season(uid,league(uid));const manual=await logManualWatchAndReconcile(uid,movie(41005),{watchedAt:"2035-01-13T10:00:00Z"});await importHistory(uid,"plex",[event(41005,"2035-01-13T12:00:00Z","delete")],getMovie,{connectionId:"delete"});const d=db.prepare("SELECT * FROM duplicate_cases WHERE user_id=? AND status='pending'").get(uid);fail(s.id,"fail_delete");await assert.rejects(deleteWatchAndReconcileAchievements(uid,manual.watch.id),/forced season/);drop("fail_delete");assert.equal(db.prepare("SELECT deleted_at FROM watches WHERE id=?").get(manual.watch.id).deleted_at,null);assert.equal(db.prepare("SELECT status FROM duplicate_cases WHERE id=?").get(d.id).status,"pending");await deleteWatchAndReconcileAchievements(uid,manual.watch.id);assert.equal(db.prepare("SELECT cancellation_reason FROM duplicate_cases WHERE id=?").get(d.id).cancellation_reason,"canonical_watch_deleted");assert.equal(roots(s.id)[0].watch_id,d.candidate_watch_id)});

test("timezone duplicate rebasing and projections roll back together",async()=>{const uid=user("timezone","UTC"),s=season(uid,league(uid));await logManualWatchAndReconcile(uid,movie(41006),{watchedAt:"2035-01-14T00:30:00Z"});await importHistory(uid,"plex",[event(41006,"2035-01-14T23:30:00Z","timezone")],getMovie,{connectionId:"timezone"});const d=db.prepare("SELECT * FROM duplicate_cases WHERE user_id=? AND status='pending'").get(uid);fail(s.id,"fail_timezone");await assert.rejects(updateUserSettings(uid,{timezone:"America/Los_Angeles"}),/forced season/);drop("fail_timezone");assert.equal(db.prepare("SELECT timezone FROM users WHERE id=?").get(uid).timezone,"UTC");assert.equal(db.prepare("SELECT status FROM duplicate_cases WHERE id=?").get(d.id).status,"pending");await updateUserSettings(uid,{timezone:"America/Los_Angeles"});assert.equal(db.prepare("SELECT cancellation_reason FROM duplicate_cases WHERE id=?").get(d.id).cancellation_reason,"timezone_no_matching_manual");assert.equal(roots(s.id).length,1)});


test("placeholder reconciliation preserves verified evidence and resolves stale duplicate state",async()=>{const uid=user("placeholder"),s=season(uid,league(uid),{mode:"verified"});await logManualWatchAndReconcile(uid,movie(42001),{watchedAt:"2035-01-15T00:00:00Z"});await importHistory(uid,"plex",[event(42001,"2035-01-15T12:00:00Z","placeholder")],getMovie,{connectionId:"placeholder"});const pending=db.prepare("SELECT id FROM duplicate_cases WHERE user_id=? AND status='pending'").get(uid);assert.ok(pending);assert.equal(roots(s.id).length,0);const preview=previewPlaceholderReconciliation(uid,uid,"2035-01-15");assert.equal(preview.candidates.length,1);applyPlaceholderReconciliation(uid,uid,{nonce:preview.nonce,previewHash:preview.preview_hash,candidateIds:[preview.candidates[0].candidate_id]});const survivor=db.prepare("SELECT source,provider_service,provider_connection_id,provider_event_id FROM watches WHERE user_id=? AND tmdb_id=42001 AND deleted_at IS NULL").get(uid);assert.deepEqual(survivor,{source:"plex",provider_service:null,provider_connection_id:null,provider_event_id:null});assert.equal(db.prepare("SELECT COUNT(*) c FROM duplicate_cases WHERE user_id=? AND status='pending'").get(uid).c,0);assert.equal(roots(s.id).length,1);assert.equal(JSON.parse(roots(s.id)[0].metadata_json).evidence_kind,"reconciled_provider")});

test("large import and timezone mutations chunk season reconciliation inside the same transaction",async()=>{const uid=user("large","UTC"),s=season(uid,league(uid));const items=[];for(let i=0;i<101;i++)items.push(event(43000+i,"2035-01-10T12:00:00Z",`large-${i}`));const r=await importHistory(uid,"plex",items,getMovie,{connectionId:"large"});assert.equal(r.imported,101);assert.equal(roots(s.id).length,101);fail(s.id,"fail_large_timezone");await assert.rejects(updateUserSettings(uid,{timezone:"America/Los_Angeles"}),/forced season/);drop("fail_large_timezone");assert.equal(db.prepare("SELECT timezone FROM users WHERE id=?").get(uid).timezone,"UTC");await updateUserSettings(uid,{timezone:"America/Los_Angeles"});assert.equal(roots(s.id).length,101)});

test("leaving an archived league does not mutate frozen participant season history",()=>{const owner=user("archive-owner"),member=user("archive-member"),l=league(owner,`Archived ${n}`),invite=createInvite(owner,l.id,{expires_at:"2036-01-01T00:00:00.000Z",max_uses:1}),token=decodeURIComponent(invite.invite_path.slice("/join#invite=".length));acceptInvite(member,token);const m=db.prepare("SELECT id,joined_at FROM league_memberships WHERE league_id=? AND user_id=? AND left_at IS NULL").get(l.id,member),starts=new Date(new Date(m.joined_at).getTime()+1).toISOString(),ends=new Date(Date.now()+86400000).toISOString(),s=season(owner,l,{participant:member,membership:m.id,starts,ends});db.prepare("UPDATE leagues SET archived_at=?,updated_at=? WHERE id=?").run(starts,starts,l.id);assert.throws(()=>leaveLeague(member,l.id),/read-only/);assert.equal(db.prepare("SELECT left_at FROM league_memberships WHERE id=?").get(m.id).left_at,null);assert.equal(db.prepare("SELECT eligible_until FROM season_members WHERE season_id=? AND user_id=?").get(s.id,member).eligible_until,null)});


test("membership cutoff and projection reversal share one immediate transaction",()=>{const owner=user("owner"),member=user("member"),l=league(owner,`Departure ${n}`),invite=createInvite(owner,l.id,{expires_at:"2036-01-01T00:00:00.000Z",max_uses:1}),token=decodeURIComponent(invite.invite_path.slice("/join#invite=".length));acceptInvite(member,token);const m=db.prepare("SELECT id,joined_at FROM league_memberships WHERE league_id=? AND user_id=? AND left_at IS NULL").get(l.id,member),starts=new Date(new Date(m.joined_at).getTime()+1).toISOString(),ends=new Date(Date.now()+86400000).toISOString(),s=season(owner,l,{participant:member,membership:m.id,starts,ends}),watchedAt=new Date(Date.now()+3600000).toISOString();insertWatch({userId:member,movie:movie(41007),watchedAt});reconcileMovieEligibility(member,[41007]);reconcileSeasonScoresForUser(member,{seasonIds:[s.id]});assert.equal(roots(s.id).length,1);fail(s.id,"fail_leave");assert.throws(()=>leaveLeague(member,l.id),/forced season/);drop("fail_leave");assert.equal(db.prepare("SELECT left_at FROM league_memberships WHERE id=?").get(m.id).left_at,null);assert.equal(db.prepare("SELECT eligible_until FROM season_members WHERE season_id=? AND user_id=?").get(s.id,member).eligible_until,null);const departure=leaveLeague(member,l.id);assert.equal(db.prepare("SELECT eligible_until FROM season_members WHERE season_id=? AND user_id=?").get(s.id,member).eligible_until,departure.left_at);assert.equal(totalScore(member,{seasonId:s.id}),0)});
