process.env.DATA_DIR = `/tmp/rs-season-scoring-${process.pid}`;
process.env.SESSION_SECRET = "test-secret-that-is-at-least-32-chars-long";
process.env.NODE_ENV = "test";
import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
const { db } = await import("../src/db.js");
const { awardScoreEvent, reverseScoreEvents, totalScore } = await import("../src/repositories/score-ledger.js");
const { reconcileSeasonScoresForUser, reconcileSeasonBatch } = await import("../src/services/season-scoring-service.js");
let n=0; const ts=(d,h="00")=>`2035-01-${String(d).padStart(2,"0")}T${h}:00:00.000Z`;
function user(p="u"){return Number(db.prepare("INSERT INTO users(username,password_hash) VALUES (?,'x')").run(`${p}-${process.pid}-${++n}`).lastInsertRowid)}
function league(uid,name=`L${n}`){const id=Number(db.prepare("INSERT INTO leagues(name,timezone,owner_user_id,created_by_user_id,created_at,updated_at) VALUES (?,'UTC',?,?,?,?)").run(name,uid,uid,ts(1),ts(1)).lastInsertRowid);const membershipId=member(id,uid);return{id,membershipId}}
function member(lid,uid){return Number(db.prepare("INSERT INTO league_memberships(league_id,user_id,role,joined_at,created_at) VALUES (?,?,'member','2034-01-01T00:00:00.000Z','2034-01-01T00:00:00.000Z')").run(lid,uid).lastInsertRowid)}
function season(uid,l,{mode="casual",from=ts(1),until=null,locked=true,participant=uid,membership=l.membershipId}={}){const id=Number(db.prepare("INSERT INTO seasons(league_id,name,mode,timezone,rule_version,starts_at,ends_at,created_by_user_id,created_at,updated_at) VALUES (?,? ,?,'UTC','season-v1',?,?,?, ?,?)").run(l.id,`S${n}-${mode}`,mode,ts(1),ts(20),uid,ts(1),ts(1)).lastInsertRowid);const sm=Number(db.prepare("INSERT INTO season_members(season_id,membership_id,user_id,username_snapshot,eligible_from,eligible_until,created_at) VALUES (?,?,?,?,?,?,?)").run(id,membership,participant,`snap-${participant}`,from,until,ts(1)).lastInsertRowid);if(locked)db.prepare("UPDATE seasons SET participants_locked_at=?,updated_at=? WHERE id=?").run(ts(1),ts(1),id);return{id,sm}}
function watch(uid,{tmdb=1,time=ts(5),source="manual",provider=false,qualifies=1,deleted=null}={}){const p=provider?[source,`c${n}`,`e${n}`]:[null,null,null];return Number(db.prepare("INSERT INTO watches(user_id,tmdb_id,title,points,source,watched_at,watched_at_utc,watched_day_local,timezone_used,qualifies_for_season,provider_service,provider_connection_id,provider_event_id,deleted_at) VALUES (?,?,?,0,?,?,?,?, 'UTC',?,?,?,?,?)").run(uid,tmdb,`M${tmdb}`,source,time.replace('T',' ').slice(0,19),time,time.slice(0,10),qualifies,...p,deleted).lastInsertRowid)}
function source(uid,wid,{category="watch_first",points=10,time=ts(5),created=time,key=n}={}){return awardScoreEvent({eventKey:`life/${wid}/${category}/${key}`,userId:uid,watchId:wid,category,points,ruleVersion:"competition-v1",metadata:{secret:"not copied"},effectiveAt:time,createdAt:created})}
const rows=sid=>db.prepare("SELECT * FROM score_events WHERE season_id=? ORDER BY id").all(sid);const roots=sid=>rows(sid).filter(x=>x.reverses_event_id==null);

test("Casual and Challenge project qualifying first/zero-cooldown/rewatch with source chronology and safe immutable metadata",()=>{const uid=user("modes"),a=season(uid,league(uid)),b=season(uid,league(uid,"challenge"),{mode:"challenge"});const specs=[["watch_first",20,ts(2)],["watch_cooldown",0,ts(3)],["watch_rewatch",5,ts(4)]];const src=specs.map(([category,points,time],i)=>source(uid,watch(uid,{tmdb:10,time}),{category,points,time,created:ts(18),key:i}));const r=reconcileSeasonScoresForUser(uid,{});assert.equal(r.added,6);for(const s of[a,b]){assert.deepEqual(roots(s.id).map(x=>[x.event_key,x.category,x.points,x.effective_at]),src.map(x=>[`season/${s.id}/watch-event/${x.id}`,x.category,x.points,x.effective_at]));for(const x of roots(s.id)){assert.equal(x.season_member_id,s.sm);const m=JSON.parse(x.metadata_json);assert.deepEqual(Object.keys(m).sort(),["evidence_kind","evidence_reference","mode","participant_cutoff","source_event_id","source_watch_id"]);assert.equal(JSON.stringify(m).includes("secret"),false)}}});

test("Verified requires direct provider or preserved active merged-provider proof",()=>{const uid=user("verified"),s=season(uid,league(uid),{mode:"verified"});const direct=watch(uid,{tmdb:21,source:"plex",provider:true});const manual=watch(uid,{tmdb:22,time:ts(6)});const merged=watch(uid,{tmdb:22,time:ts(6,"01"),source:"trakt",provider:true,deleted:ts(7)});db.prepare("UPDATE watches SET deleted_reason='duplicate_merged',logical_canonical_watch_id=? WHERE id=?").run(manual,merged);db.prepare("INSERT INTO duplicate_cases(user_id,fingerprint,canonical_watch_id,candidate_watch_id,status,resolution,evidence_json,created_at,resolved_at) VALUES (?,?,?,?,'resolved','merge','{}',?,?)").run(uid,`f${n}`,manual,merged,ts(6),ts(7));const none=watch(uid,{tmdb:23,time:ts(8)});const wanted=[source(uid,direct),source(uid,manual,{time:ts(6)})];source(uid,none,{time:ts(8)});reconcileSeasonScoresForUser(uid,{});assert.deepEqual(roots(s.id).map(x=>x.projection_source_event_id),wanted.map(x=>x.id));assert.deepEqual(roots(s.id).map(x=>{const m=JSON.parse(x.metadata_json);return [m.evidence_kind,m.evidence_reference]}),[["direct_provider",`watch/${direct}`],["merged_provider",`duplicate/${db.prepare("SELECT id FROM duplicate_cases WHERE candidate_watch_id=?").get(merged).id}/watch/${merged}`]]);n+=1;const replacement=watch(uid,{tmdb:22,time:ts(6,"02"),source:"plex",provider:true,deleted:ts(8)});db.prepare("UPDATE watches SET deleted_reason='duplicate_merged',logical_canonical_watch_id=? WHERE id=?").run(manual,replacement);db.prepare("INSERT INTO duplicate_cases(user_id,fingerprint,canonical_watch_id,candidate_watch_id,status,resolution,evidence_json,created_at,resolved_at) VALUES (?,?,?,?,'resolved','merge','{}',?,?)").run(uid,`replacement-${n}`,manual,replacement,ts(7),ts(8));db.prepare("UPDATE duplicate_cases SET cancelled_at=?,cancellation_reason='replaced' WHERE candidate_watch_id=?").run(ts(9),merged);const changed=reconcileSeasonScoresForUser(uid,{tmdbIds:[22]});assert.deepEqual([changed.reversed,changed.reactivated,totalScore(uid,{seasonId:s.id})],[1,1,20]);const leaf=rows(s.id).at(-1);assert.equal(JSON.parse(leaf.metadata_json).projection_context.evidence_reference,`duplicate/${db.prepare("SELECT id FROM duplicate_cases WHERE candidate_watch_id=?").get(replacement).id}/watch/${replacement}`);db.prepare("UPDATE duplicate_cases SET cancelled_at=?,cancellation_reason='test' WHERE candidate_watch_id=?").run(ts(10),replacement);assert.equal(reconcileSeasonScoresForUser(uid,{tmdbIds:[22]}).reversed,1)});

test("locked snapshots and exact season/participant half-open bounds use effective_at, not created_at or active membership",()=>{const owner=user("bounds-owner"),uid=user("bounds"),l=league(owner),membership=member(l.id,uid),s=season(owner,l,{participant:uid,membership,until:ts(10)});db.prepare("UPDATE league_memberships SET left_at=? WHERE id=?").run(ts(10),membership);const times=["2034-12-31T23:59:59.999Z",ts(1),ts(9,"23"),ts(10),ts(20)];const ids=times.map((time,i)=>source(uid,watch(uid,{tmdb:30+i,time}),{time,created:ts(25),key:i}).id);reconcileSeasonScoresForUser(uid,{});assert.deepEqual(roots(s.id).map(x=>x.projection_source_event_id),[ids[1],ids[2]]);const unlocked=season(uid,league(uid,"unlocked"),{locked:false});reconcileSeasonScoresForUser(uid,{});assert.equal(roots(unlocked.id).length,0)});

test("reissued lifetime sources replace old projections; removal/reactivation is append-only, isolated, and idempotent",()=>{const uid=user("repair"),s1=season(uid,league(uid)),s2=season(uid,league(uid,"other"));const wid=watch(uid,{tmdb:41}),first=source(uid,wid,{points:20,key:1});reconcileSeasonScoresForUser(uid,{seasonIds:[s1.id]});reverseScoreEvents({userId:uid,eventIds:[first.id],reason:"reissued",reversedAt:ts(8)});const second=source(uid,wid,{category:"watch_rewatch",points:5,key:2});let r=reconcileSeasonScoresForUser(uid,{seasonIds:[s1.id],tmdbIds:[41]});assert.deepEqual([r.added,r.reversed,totalScore(uid,{seasonId:s1.id})],[1,1,5]);assert.equal(rows(s2.id).length,0);db.prepare("UPDATE watches SET qualifies_for_season=0 WHERE id=?").run(wid);assert.equal(reconcileSeasonScoresForUser(uid,{seasonIds:[s1.id]}).reversed,1);db.prepare("UPDATE watches SET qualifies_for_season=1 WHERE id=?").run(wid);assert.equal(reconcileSeasonScoresForUser(uid,{seasonIds:[s1.id]}).reactivated,1);assert.equal(totalScore(uid,{seasonId:s1.id}),5);assert.equal(reconcileSeasonScoresForUser(uid,{seasonIds:[s1.id]}).added,0);assert.ok(rows(s1.id).some(x=>x.event_key===`reverse/reverse/season/${s1.id}/watch-event/${second.id}`))});

test("forced late reversal failure rolls back prior addition",()=>{const uid=user("rollback"),s=season(uid,league(uid));const old=watch(uid,{tmdb:51});source(uid,old);reconcileSeasonScoresForUser(uid,{});db.prepare("UPDATE watches SET qualifies_for_season=0 WHERE id=?").run(old);source(uid,watch(uid,{tmdb:52,time:ts(6)}),{time:ts(6)});db.exec(`CREATE TEMP TRIGGER force_fail BEFORE INSERT ON score_events WHEN NEW.season_id=${s.id} AND NEW.reverses_event_id IS NOT NULL BEGIN SELECT RAISE(ABORT,'forced rollback'); END;`);assert.throws(()=>reconcileSeasonScoresForUser(uid,{}),/forced rollback/);db.exec("DROP TRIGGER force_fail");assert.equal(roots(s.id).length,1);assert.equal(roots(s.id)[0].reversed_at,null);reconcileSeasonScoresForUser(uid,{});assert.equal(roots(s.id).length,2)});

test("frozen seasons skip writes; inputs and batch cursor are strict and bounded",()=>{const owner=user("batch"),l=league(owner),others=[user("a"),user("b")],members=[l.membershipId,member(l.id,others[0]),member(l.id,others[1])];const sid=Number(db.prepare("INSERT INTO seasons(league_id,name,mode,timezone,rule_version,starts_at,ends_at,created_by_user_id,created_at,updated_at) VALUES (?,'Batch','casual','UTC','v1',?,?,?, ?,?)").run(l.id,ts(1),ts(20),owner,ts(1),ts(1)).lastInsertRowid);[owner,...others].forEach((uid,i)=>db.prepare("INSERT INTO season_members(season_id,membership_id,user_id,username_snapshot,eligible_from,created_at) VALUES (?,?,?,?,?,?)").run(sid,members[i],uid,`u${uid}`,ts(1),ts(1)));db.prepare("UPDATE seasons SET participants_locked_at=?,updated_at=? WHERE id=?").run(ts(1),ts(1),sid);[owner,...others].forEach((uid,i)=>source(uid,watch(uid,{tmdb:60+i})));for(const bad of ["1",0,true,1.5,NaN])assert.throws(()=>reconcileSeasonScoresForUser(bad,{}),/positive integer/);for(const opts of [null,[],{x:1},{tmdbIds:1},{tmdbIds:["1"]},{seasonIds:[0]},{tmdbIds:Array.from({length:101},(_,i)=>i+1)}])assert.throws(()=>reconcileSeasonScoresForUser(owner,opts),/object|unsupported|array|positive integer|at most/);for(const opts of [{x:1},{afterUserId:"1"},{limit:0},{limit:101},{limit:1.5}])assert.throws(()=>reconcileSeasonBatch(sid,opts),/unsupported|positive integer|between 1 and 100/);const one=reconcileSeasonBatch(sid,{limit:2});assert.deepEqual([one.processed,one.done],[2,false]);const two=reconcileSeasonBatch(sid,{afterUserId:one.nextCursor,limit:2});assert.deepEqual([two.processed,two.done,roots(sid).length],[1,true,3]);db.prepare("UPDATE seasons SET finalized_at=?,updated_at=? WHERE id=?").run(ts(25),ts(25),sid);const frozen=reconcileSeasonScoresForUser(owner,{seasonIds:[sid]});assert.deepEqual(frozen.frozenSeasonIds,[sid]);assert.equal(reconcileSeasonBatch(sid,{}).frozen,true)});

test("concurrent process replay serializes to one projection",async()=>{const uid=user("race"),s=season(uid,league(uid));source(uid,watch(uid,{tmdb:71}));const code=`const {reconcileSeasonScoresForUser}=await import('./src/services/season-scoring-service.js');reconcileSeasonScoresForUser(Number(process.argv[1]),{seasonIds:[Number(process.argv[2])]})`;const run=()=>new Promise(resolve=>{const p=spawn(process.execPath,["--input-type=module","-e",code,String(uid),String(s.id)],{cwd:process.cwd(),env:process.env,stdio:["ignore","ignore","pipe"]});let e="";p.stderr.on("data",x=>e+=x);p.on("close",c=>resolve({c,e}))});const out=await Promise.all([run(),run()]);assert.deepEqual(out.map(x=>x.c),[0,0],out.map(x=>x.e).join("\n"));assert.equal(roots(s.id).length,1)});


test("participant cutoff changes preserve earlier projections and reverse only newly out-of-window sources",()=>{const owner=user("cutoff-owner"),uid=user("cutoff"),l=league(owner),membership=member(l.id,uid),s=season(owner,l,{participant:uid,membership});const before=source(uid,watch(uid,{tmdb:81,time:ts(5)}),{time:ts(5)}),after=source(uid,watch(uid,{tmdb:82,time:ts(15)}),{time:ts(15)});reconcileSeasonScoresForUser(uid,{});db.prepare("UPDATE season_members SET eligible_until=? WHERE id=?").run(ts(10),s.sm);const result=reconcileSeasonScoresForUser(uid,{});assert.deepEqual([result.reversed,result.unchanged,totalScore(uid,{seasonId:s.id})],[1,1,before.points]);assert.equal(roots(s.id).find(x=>x.projection_source_event_id===before.id).reversed_at,null);assert.notEqual(roots(s.id).find(x=>x.projection_source_event_id===after.id).reversed_at,null)});

test("deleted sources reverse, while archived and cancelled seasons are frozen read-only",()=>{const uid=user("freeze"),l=league(uid),active=season(uid,l),cancelled=season(uid,league(uid,"cancelled"));db.prepare("UPDATE seasons SET cancelled_at=?,updated_at=? WHERE id=?").run(ts(1),ts(1),cancelled.id);const wid=watch(uid,{tmdb:91});source(uid,wid);reconcileSeasonScoresForUser(uid,{seasonIds:[active.id]});db.prepare("UPDATE watches SET deleted_at=? WHERE id=?").run(ts(8),wid);assert.equal(reconcileSeasonScoresForUser(uid,{seasonIds:[active.id]}).reversed,1);db.prepare("UPDATE leagues SET archived_at=?,updated_at=? WHERE id=?").run(ts(9),ts(9),l.id);db.prepare("UPDATE watches SET deleted_at=NULL WHERE id=?").run(wid);const frozen=reconcileSeasonScoresForUser(uid,{});assert.deepEqual(frozen.frozenSeasonIds,[active.id,cancelled.id]);assert.equal(frozen.reactivated,0);assert.equal(reconcileSeasonBatch(active.id,{}).frozen,true)});

test("unlocked batches are not ready and optional cursor rejects null",()=>{const uid=user("unlocked-batch"),s=season(uid,league(uid),{locked:false});assert.deepEqual([reconcileSeasonBatch(s.id,{}).ready,reconcileSeasonBatch(s.id,{}).processed],[false,0]);assert.throws(()=>reconcileSeasonBatch(s.id,{afterUserId:null}),/positive integer/)});


test("database boundaries reject forged projections, malformed reversals, archived writes, and mutable provider identity",()=>{const uid=user("db-guards"),l=league(uid),s=season(uid,l),wid=watch(uid,{tmdb:101,source:"plex",provider:true}),life=source(uid,wid,{points:23,time:ts(5)});assert.throws(()=>db.prepare(`INSERT INTO score_events(event_key,user_id,watch_id,season_id,projection_source_event_id,season_member_id,category,points,rule_version,effective_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).run(`forged/${s.id}`,uid,wid,s.id,life.id,s.sm,life.category,999,life.rule_version,life.effective_at),/exactly copy/i);reconcileSeasonScoresForUser(uid,{seasonIds:[s.id]});const root=roots(s.id)[0];assert.throws(()=>db.prepare(`INSERT INTO score_events(event_key,user_id,watch_id,season_id,projection_source_event_id,season_member_id,category,points,rule_version,effective_at,reverses_event_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).run(`bad-reverse/${root.id}`,uid,wid,s.id,life.id,s.sm,root.category,-999,root.rule_version,root.effective_at,root.id),/exactly compensate/i);assert.throws(()=>db.prepare("UPDATE score_events SET reversed_at=? WHERE id=?").run(ts(8),root.id),/derived and immutable/i);assert.throws(()=>db.prepare("UPDATE watches SET provider_event_id=? WHERE id=?").run("replacement",wid),/provider watch identity is immutable/i);assert.throws(()=>db.prepare("INSERT INTO watches(user_id,tmdb_id,title,points,source,watched_at,provider_service,provider_connection_id,provider_event_id) VALUES (?,?,?,0,'trakt',?,'plex','c','e')").run(uid,102,"bad-provider","2035-01-05 00:00:00"),/incomplete or inconsistent/i);db.prepare("UPDATE leagues SET archived_at=?,updated_at=? WHERE id=?").run(ts(9),ts(9),l.id);assert.throws(()=>db.prepare("INSERT INTO score_events(event_key,user_id,season_id,season_member_id,category,points,rule_version,effective_at) VALUES (?,?,?,?,?,?,?,?)").run(`archived/${s.id}`,uid,s.id,s.sm,"challenge_bonus",5,"v1",ts(5)),/season standings.*immutable/i);assert.throws(()=>reverseScoreEvents({userId:uid,eventIds:[root.id],reason:"archived"}),/season standings.*immutable/i)});


test("batch repair reports a conflicting user and advances to later participants",()=>{const owner=user("batch-progress"),bad=user("batch-bad"),good=user("batch-good"),l=league(owner),members=[l.membershipId,member(l.id,bad),member(l.id,good)],seasonId=Number(db.prepare("INSERT INTO seasons(league_id,name,mode,timezone,rule_version,starts_at,ends_at,created_by_user_id,created_at,updated_at) VALUES (?,'Progress','casual','UTC','v1',?,?,?,?,?)").run(l.id,ts(1),ts(20),owner,ts(1),ts(1)).lastInsertRowid);[owner,bad,good].forEach((uid,i)=>db.prepare("INSERT INTO season_members(season_id,membership_id,user_id,username_snapshot,eligible_from,created_at) VALUES (?,?,?,?,?,?)").run(seasonId,members[i],uid,`u${uid}`,ts(1),ts(1)));db.prepare("UPDATE seasons SET participants_locked_at=?,updated_at=? WHERE id=?").run(ts(1),ts(1),seasonId);source(bad,watch(bad,{tmdb:111}));source(good,watch(good,{tmdb:112}));db.exec(`CREATE TEMP TRIGGER fail_one_projection BEFORE INSERT ON score_events WHEN NEW.season_id=${seasonId} AND NEW.user_id=${bad} BEGIN SELECT RAISE(ABORT,'one user is corrupt'); END;`);const result=reconcileSeasonBatch(seasonId,{limit:10});db.exec("DROP TRIGGER fail_one_projection");assert.deepEqual([result.processed,result.failed,result.done],[3,1,true]);assert.deepEqual(result.failedUserIds,[bad]);assert.equal(db.prepare("SELECT COUNT(*) count FROM score_events WHERE season_id=? AND user_id=?").get(seasonId,good).count,1)});


test("database projection guard rejects every service-ineligible root and illegal nested reversal",()=>{
  const uid=user("raw-guard"),l=league(uid),s=season(uid,l);
  const insertProjection=(seasonRow,event,eventKey=`season/${seasonRow.id}/watch-event/${event.id}`)=>db.prepare("INSERT INTO score_events(event_key,user_id,watch_id,season_id,projection_source_event_id,season_member_id,category,points,rule_version,metadata_json,created_at,effective_at) VALUES (?,?,?,?,?,?,?,?,?,'{}',?,?)").run(eventKey,event.user_id,event.watch_id,seasonRow.id,event.id,seasonRow.sm,event.category,event.points,event.rule_version,ts(12),event.effective_at);
  const valid=source(uid,watch(uid,{tmdb:201}));
  assert.throws(()=>insertProjection(s,valid,"forged/non-deterministic"),/eligible lifetime source/);
  const reversed=source(uid,watch(uid,{tmdb:202}));reverseScoreEvents({userId:uid,eventIds:[reversed.id],reason:"removed",reversedAt:ts(11)});
  assert.throws(()=>insertProjection(s,reversed),/eligible lifetime source/);
  const deleted=source(uid,watch(uid,{tmdb:203,deleted:ts(9)}));assert.throws(()=>insertProjection(s,deleted),/eligible lifetime source/);
  const disqualified=source(uid,watch(uid,{tmdb:204,qualifies:0}));assert.throws(()=>insertProjection(s,disqualified),/eligible lifetime source/);
  const late=source(uid,watch(uid,{tmdb:205,time:ts(20)}),{time:ts(20)});assert.throws(()=>insertProjection(s,late),/eligible lifetime source/);
  const cutoff=season(uid,league(uid,"cutoff-guard"),{until:ts(5)}),afterCutoff=source(uid,watch(uid,{tmdb:206,time:ts(6)}),{time:ts(6)});assert.throws(()=>insertProjection(cutoff,afterCutoff),/eligible lifetime source/);
  const unlocked=season(uid,league(uid,"unlock-guard"),{locked:false}),unlockSource=source(uid,watch(uid,{tmdb:207}));assert.throws(()=>insertProjection(unlocked,unlockSource),/eligible lifetime source/);
  const verified=season(uid,league(uid,"verified-guard"),{mode:"verified"}),manual=source(uid,watch(uid,{tmdb:208}));assert.throws(()=>insertProjection(verified,manual),/eligible lifetime source/);
  const wrongCategory=source(uid,watch(uid,{tmdb:209}),{category:"achievement",points:1});assert.throws(()=>insertProjection(s,wrongCategory),/eligible lifetime source/);
  const lifetimeChild=db.prepare("SELECT * FROM score_events WHERE reverses_event_id=?").get(reversed.id);
  assert.throws(()=>db.prepare("INSERT INTO score_events(event_key,user_id,watch_id,category,points,rule_version,metadata_json,created_at,effective_at,reverses_event_id) VALUES (?,?,?,?,?,?, '{}',?,?,?)").run("illegal/lifetime/reactivation",uid,lifetimeChild.watch_id,lifetimeChild.category,-lifetimeChild.points,lifetimeChild.rule_version,ts(12),lifetimeChild.effective_at,lifetimeChild.id),/exactly compensate/);
  const bonus=awardScoreEvent({eventKey:`season/${s.id}/bonus/raw`,userId:uid,seasonId:s.id,seasonMemberId:s.sm,category:"challenge_bonus",points:3,ruleVersion:"challenge-v1",metadata:{},effectiveAt:ts(5),createdAt:ts(5)});
  reverseScoreEvents({userId:uid,eventIds:[bonus.id],reason:"bonus removed",reversedAt:ts(12)});
  const bonusChild=db.prepare("SELECT * FROM score_events WHERE reverses_event_id=?").get(bonus.id);
  assert.throws(()=>db.prepare("INSERT INTO score_events(event_key,user_id,season_id,season_member_id,category,points,rule_version,metadata_json,created_at,effective_at,reverses_event_id) VALUES (?,?,?,?,?,?,?,'{}',?,?,?)").run("illegal/bonus/reactivation",uid,s.id,s.sm,bonusChild.category,-bonusChild.points,bonusChild.rule_version,ts(13),bonusChild.effective_at,bonusChild.id),/exactly compensate/);
});
